#ifndef ROBOSIGNAL_ROBOSIGNAL_GLOBAL_HPP
#define ROBOSIGNAL_ROBOSIGNAL_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(ROBOSIGNAL_LIBRARY)
#  define ROBOSIGNALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROBOSIGNALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
